services:

  nginx:
    image: nginx:alpine
    volumes:
     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./:/var/www/
    ports:
     - "80:80"
    networks:
     - web
    depends_on:
     - php

  php:
    build:
      dockerfile: .docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
        - 'host..docker.internal:host-gateway'
    volumes:
        - ./:/var/www/
    networks:
        - web

  pgsql:
      image: postgres:16.2
      ports:
          - "5432:5432"
      volumes:
          - pgsql_database:/var/lib/postgresql/data
      environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      networks:
          - web

networks:
  web:
    driver: bridge

volumes:
  pgsql_database:
    driver: local
