version: '3'
services:

#Nginx Server
  nginx:
    build:
      context: docker/nginx
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "8080:80"
      - "8433:443"
    depends_on:
      - php

#PHP
  php:
    build:
      context: docker/php
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./src:/var/www/html
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

#NPM
  npm:
    image: node:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "3009:3009"

#MySQL
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: root
