services:

  nginx:
    image: nginx:alpine
    volumes:
     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./:/var/www/
    ports:
     - "80:80"
    networks:
     - web
    depends_on:
     - php

  php:
    build:
      dockerfile: .docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
        - 'host..docker.internal:host-gateway'
    volumes:
        - ./:/var/www/
    networks:
        - web

  mysql:
    image: mysql:8.3
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql_database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  mysql_database:
    driver: local
